export const TIMER_LIMITS = {
  FOCUS_MINUTES_MIN: 5,
  FOCUS_MINUTES_MAX: 120,
  BREAK_MINUTES_MIN: 0,
  BREAK_MINUTES_MAX: 60,
  CYCLES_MIN: 1,
  CYCLES_MAX: 10,
} as const;

export const FOCUS_PERIOD_LIMITS = {
  MIN_FOCUS_SECONDS: 5,
  MAX_PAUSE_MERGE_SECONDS: 5,
  MAX_PERIODS: 100,
} as const;

export const CATEGORY_LIMITS = {
  COUNT_MAX: 10,
} as const;

export const AUTH_LIMITS = {
  PASSWORD_MIN_LENGTH: 8,
} as const;

export const INPUT_LIMITS = {
  NOTE_MAX_LENGTH: 500,
  NICKNAME_MAX_LENGTH: 20,
  MESSAGE_LENGTH_MIN: 1,
  MESSAGE_LENGTH_MAX: 200,
  MESSAGE_COUNT_MIN: 1,
  MESSAGE_COUNT_MAX: 20,
  CATEGORIES_MAX: 10,
} as const;
