export { TIMER_LIMITS, FOCUS_PERIOD_LIMITS } from '@pomodash/shared';

export const INPUT_LIMITS = {
  NOTE_MAX_LENGTH: 500,
  NICKNAME_MAX_LENGTH: 20,
  MESSAGE_LENGTH_MIN: 1,
  MESSAGE_LENGTH_MAX: 200,
  MESSAGE_COUNT_MIN: 1,
  MESSAGE_COUNT_MAX: 20,
  CATEGORIES_MAX: 10,
} as const;

export const SOUND_LIMITS = {
  VOLUME_MIN: 0,
  VOLUME_MAX: 100,
  REPEAT_MIN: 1,
  REPEAT_MAX: 5,
} as const;

export const SESSION_LIMITS = {
  ABANDONED_CHECK_INTERVAL_MS: 30 * 1000,
} as const;

export const AUTH_LIMITS = {
  PASSWORD_MIN_LENGTH: 8,
} as const;

export const STORAGE_VERSION = 1;
